services:
    rulerz.compiler:
        alias: rulerz.compiler.eval

    rulerz.compiler.eval:
        class:      RulerZ\Compiler\EvalCompiler
        arguments:  [ @rulerz.parser ]
        public: false
