services:
    rulerz:
        class:      RulerZ\RulerZ
        arguments:  [ @rulerz.compiler ]

    rulerz.compiler:
        alias:  rulerz.compiler.file
        public: false

    rulerz.compiler.file:
        class:      RulerZ\Compiler\FileCompiler
        public:     false
        arguments:  [ @rulerz.parser, %rulerz.cache_directory% ]

    rulerz.parser:
        class:  RulerZ\Parser\HoaParser
        public: false

    rulerz.executor.array:
        class:  RulerZ\Compiler\Target\ArrayVisitor
        public: false
        tags:
            - { name: rulerz.executor }
