services:
    rulerz:
        class:      RulerZ\RulerZ
        arguments:  [ @rulerz.compiler ]

    rulerz.compiler:
        alias:  rulerz.compiler.file
        public: false

    rulerz.compiler.file:
        class:      RulerZ\Compiler\FileCompiler
        public:     false
        arguments:  [ @rulerz.parser, %rulerz.cache_directory% ]

    rulerz.parser:
        class:  RulerZ\Parser\HoaParser
        public: false

    rulerz.executor.doctrine_orm:
        class:  RulerZ\Compiler\Target\Sql\DoctrineQueryBuilderVisitor
        public: false
        tags:
            - { name: rulerz.executor }

    rulerz.executor.array:
        class:  RulerZ\Compiler\Target\ArrayVisitor
        public: false
        tags:
            - { name: rulerz.executor }

#    rulerz.executor.elasticsearch:
#        class:  RulerZ\Executor\ElasticsearchExecutor
#        public: false
#        tags:
#            - { name: rulerz.executor }
#
#    rulerz.executor.elastica:
#        class:  RulerZ\Executor\ElasticaExecutor
#        public: false
#        tags:
#            - { name: rulerz.executor }
