services:
    rulerz.validator.unique.rule_validator:
        class: Symfony\Bridge\RulerZ\Validator\Constraints\RuleValidator
        arguments: [ "@rulerz.parser" ]
        tags:
            - { name: validator.constraint_validator, alias: rulerz_rule_validator }
